name: School of Magix
favicon: null
layout_spectrum: 0.31620116950944066
typography_spectrum: 0.8496604787651449
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.6384732858277857
  saturation: 0.6147439954802394
  rhythmicContrast: 0.1666599423624575
purpose: []
